### ISSUE TITLE
メニューボタンがずれる問題の解決

### ISSUE THREAD

**Issue by Prokuma** [Kyutech-C3/OpenCampus2021#106]
メニューがsafariで正常動作しない #85 は解決済みだが、これによってメニューボタンがヘッダーでずれる問題が発生する。これを解決する。

**Comment by Prokuma** [comment]
環境によってはずれる問題があるみたいです

**Comment by Prokuma** [comment]
#99 と関係あるかもしれません、#99 で解決されたらこのissueは閉じます

**Comment by citrus-candy** [comment]
#99 解決してました
