### ISSUE TITLE
AboutC3のスマホでのデザインの修正

### ISSUE THREAD

**Issue by Prokuma** [Kyutech-C3/OpenCampus2021#141]
![2021-07-18_20-51](https://user-images.githubusercontent.com/6737884/126065947-92f60c7a-ad0b-4d1f-9af5-31e073d52795.png)
スマホでのデザインがこうなる
これを修正する

**Comment by Kosuke-Ukita** [comment]
左右のパディングかマージンがメッセージの部分だけしか対応していなかったのでその部分をコピペすれば問題ないと思われます．すぐできるので僕しときます
