### ISSUE TITLE
PC版の作品一覧の左右の余白をもう少し増やす

### ISSUE THREAD

**Issue by Simo-C3** [Kyutech-C3/OpenCampus2021#149]

**Comment by suu-u522** [comment]
ここもう少し具体的に問題点を書いてほしいです。
別のissueでこのissueにかかわるような変更を加えたので現在のdevelopブランチで確認してもらえますか？
問題なかったらこのissueは閉じてください。

**Comment by Simo-C3** [comment]
現段階のdevelopブランチの確認しました。
画面最大サイズのときの左右の余白がまだ小さいです。ここの余白の実装をどのようにしてるかは把握してないので具体的な値は出しにくいですが、画面最大サイズぐらいのときに200pxぐらいほしいです。ただpx指定だと横幅が小さくなったときにデザインが崩れるのでその辺の調整は任せます。

**Comment by suu-u522** [comment]
文字だけでは伝わりにくいのでスクショ貼ってくれると助かります！！

**Comment by suu-u522** [comment]
一緒に作業しよ！
