### ISSUE TITLE
トップページとかにアニメーション付けたい

### ISSUE THREAD

**Issue by Simo-C3** [Kyutech-C3/OpenCampus2021#157]

**Comment by Kosuke-Ukita** [comment]
AboutC3とメッセージの部分をスクロールと同時に下からフェードインするアニメーションを作ってみたい
取り掛かります

**Comment by Kosuke-Ukita** [comment]
頑張ってるんだけど難しいなぁだれかわかるひとおしえてぇぇ
スクロール位置座標を取得する方法だけでいいんでお願いします

**Comment by Simo-C3** [comment]
ごめん
アニメーションは力になれなさそう
