### ISSUE TITLE
作品詳細ページに表示されていない情報がある

### ISSUE THREAD

**Issue by Prokuma** [Kyutech-C3/OpenCampus2021#182]
Work URLが表示されず、更新時刻がすべて同じ時間になっている

**Comment by rkun123** [comment]
@Prokuma @Simo-C3 更新時刻は、投稿をした時間なので作品にもあまり関係がないし、そもそもバックエンドでは記録していないため、必要ないかと思います。

**Comment by Simo-C3** [comment]
確かにそうですね
無くしますか？

**Comment by rkun123** [comment]
ついでに #185 もやりました
