### ISSUE TITLE
Twitterカードを設定しませんか

### ISSUE THREAD

**Issue by suu-u522** [Kyutech-C3/OpenCampus2021#189]
参考です。
https://saruwakakun.com/html-css/reference/twitter-card

タイプはwith Large Imageでいいかなと思っています。

![image](https://user-images.githubusercontent.com/65497260/126169604-0cca2b2b-a88e-41a2-89ef-4ba364be4d4d.png)

**Comment by Simo-C3** [comment]
いいですね！！！
お願いしてもいいですか？

**Comment by suu-u522** [comment]
simoくんやってくれたんやね！！！
ありがとう！！
