### ISSUE TITLE
カルーセルのページ変更ができなくなる場面がある

### ISSUE THREAD

**Issue by rkun123** [Kyutech-C3/OpenCampus2021#197]
## 再現
1. カルーセルが全幅になるようウィンドウサイズを調整
2. 一覧ページからカードをクリックして作品詳細にアクセス（RouterLinkを用いた遷移のときのみ再現？）
3. カルーセルを**ドラッグ、及びボタンでページ遷移させようとしても、前のページに戻される**
4. ウィンドウサイズを変更、またはリロードを行うと正常に戻る

**Comment by rkun123** [comment]
![EKFGRkycph](https://user-images.githubusercontent.com/12907598/126291154-d7cca814-526e-4aeb-b57e-dc301185add2.gif)

**Comment by suu-u522** [comment]
少し変更を加えました。私の環境ではうまくいったっぽいので他の方の環境ではどうでしょうか
