### ISSUE TITLE
hackのサムネ画像のコンペするぞ！！！みんな投稿しろおおおおお

### ISSUE THREAD

**Issue by Simo-C3** [Kyutech-C3/OpenCampus2021#222]

**Comment by PigeonsHouse** [comment]
映えるのはあんまりなかったですが
![image](https://user-images.githubusercontent.com/65777862/126359450-7d700043-1a10-4b58-aac2-f35994909f2a.png)
![image](https://user-images.githubusercontent.com/65777862/126359697-9c540bd3-884e-4af6-8890-00c6acbe7349.png)
![image](https://user-images.githubusercontent.com/65777862/126359904-02cd0633-c669-438e-8ca9-59b3f28c1b73.png)

**Comment by Kosuke-Ukita** [comment]
![ダウンロード](https://user-images.githubusercontent.com/82579992/126440449-838d2f0a-075f-4784-a234-37c9e214b968.jpg)
![mv024](https://user-images.githubusercontent.com/82579992/126440481-7a2a20bc-2721-4429-8f14-22a2e5554081.jpg)
![html-e1566357229823](https://user-images.githubusercontent.com/82579992/126440522-21d80d78-8cb4-465b-b1d1-9f4ebc4589cd.jpg)
![Coding](https://user-images.githubusercontent.com/82579992/126440540-ee7e43c1-9dfd-46a2-a265-e0019ff6db68.jpg)
![self-study-languages_dsmftu](https://user-images.githubusercontent.com/82579992/126440555-a7fbcbea-e502-44e3-98a7-0b78fff152e9.jpg)

**Comment by Simo-C3** [comment]
![CardList - Cardlist 1 ⋅ Storybook - Google Chrome 2021_07_21 17_52_20 (2)](https://user-images.githubusercontent.com/65708479/126461086-5e71f9fc-3236-4ef3-96a9-b7651f0fa37e.png)
![_community_id vue - Open-Campus-2021  WSL_ Ubuntu-20 04  - Visual Studio Code 2021_07_21 17_51_16](https://user-images.githubusercontent.com/65708479/126461092-c79867e5-0c77-49a0-9c89-98b73e2ca32f.png)

**Comment by Simo-C3** [comment]
![2021-07-21](https://user-images.githubusercontent.com/65708479/126461470-ba351034-7734-4d1a-b14c-b8855e154555.png)

**Comment by Simo-C3** [comment]
![_DSC2570](https://user-images.githubusercontent.com/65708479/126462107-d247d3e0-094b-4f74-b5c9-c4578a51f057.JPG)
![_DSC2563](https://user-images.githubusercontent.com/65708479/126462145-75e1985b-5e0e-4cee-b40b-04cd7b4dbe6e.JPG)
![_DSC2568](https://user-images.githubusercontent.com/65708479/126462168-e89d2f57-f105-4b5e-a65c-9e775b37814b.JPG)

**Comment by rkun123** [comment]
![IMG_20210721_175506__01.jpg](https://user-images.githubusercontent.com/12907598/126473311-63e6a941-29ec-4014-bde8-7776900e164b.jpg)

**Comment by 0xfab0131** [comment]
![k](https://user-images.githubusercontent.com/65708470/126498024-6347fb1f-27f0-41cf-b8ea-39a4a9d68c20.jpg)
