### ISSUE TITLE
`layout/default.vue`へHeaderとFooterを埋め込む

### ISSUE THREAD

**Issue by rkun123** [Kyutech-C3/OpenCampus2021#54]
## 提案
- 各ページで共通なので、HeaderとFooterは`layout/default.vue`で保持すべきかなと思いました。
- 加えて、左右のマージンもレイアウトで定義すれば、各ページで左右のマージンが変わるといったことも無くていいかなと思うんですけど、どうです？
@PigeonsHouse @citrus-candy @Prokuma

**Comment by Prokuma** [comment]
Footerは共通ですが、Headerはトップページでは使いません。Footerについては`layout/default.vue`で保持してもいいのではないかと思います。

**Comment by rkun123** [comment]
Top用のレイアウトも追加で作ろうか

**Comment by Prokuma** [comment]
そうした方がいいと思ふ

**Comment by rkun123** [comment]
それかdefaut.vue上で、もしパスが`/`だったらヘッダー非表示にするロジックをもたせようか。
ヘッダー表示非表示以外全く同じレイアウトを2ファイルで用意するのが嫌すぎる

**Comment by Prokuma** [comment]
そうした方が良さそうね

**Comment by rkun123** [comment]
レイアウトに共通のパディングを`3rem`分もたせてるけど、他のページとの兼ね合いを確認して、いらなそうなら消しましょうぞ。
